# Generated by Django 4.1.2 on 2022-10-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_puzzle_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
